package oxygen.executable

import java.nio.charset.StandardCharsets
import java.nio.file.{Files, Paths}
import oxygen.cli.*
import oxygen.predef.core.*
import oxygen.predef.zio.*
import oxygen.zio.JarUtils
import zio.*

object AutoComplete {

  private def generateScriptText(
      targetPath: String,
      scriptPath: String,
      isNative: Boolean,
      baseName: String,
      programArgs: List[String],
  ): String = {
    val functionName = s"__oxygen_cli_complete__$baseName"
    val programArgsString =
      if programArgs.nonEmpty then s"\n         ${programArgs.map(_.unesc("\"")).mkString(" ")} \\" else ""

    val end =
      if isNative then
        s"""complete -F $functionName $baseName
           |complete -F $functionName ./$baseName""".stripMargin
      else
        s"""
           |if [[ "$$1" == "--:" && "$$2" == "export" ]]; then
           |    alias $baseName="$scriptPath"
           |    complete -F $functionName $scriptPath
           |    complete -F $functionName $baseName
           |else
           |    java -jar $targetPath \\$programArgsString
           |         "$$@"
           |fi
           |""".stripMargin

    s"""#!/usr/bin/env bash
       |
       |# Auto-generated by oxygen-executable-2. Requires bash (macOS: brew install bash).
       |
       |$functionName() {
       |  local comp__join_str=$$'\\n-----separator-----\\n'
       |  local comp__num_words=$$(( $${#COMP_WORDS[@]} - 1 ))
       |  local comp__command=""
       |  local comp__acc_args=""
       |  local comp__arg_idx=$$(( COMP_CWORD - 1 ))
       |
       |  for tmp_word in "$${COMP_WORDS[@]}"; do
       |    if [[ -z "$$comp__command" ]]; then
       |      comp__command="$$tmp_word"
       |    elif [[ -z "$$comp__acc_args" ]]; then
       |      comp__acc_args="$$tmp_word"
       |    else
       |      comp__acc_args="$$comp__acc_args$$comp__join_str$$tmp_word"
       |    fi
       |  done
       |
       |  comp__raw_result=$$( \\
       |    OXYGEN_CLI_COMPLETE__NUM_WORDS="$$comp__num_words" \\
       |    OXYGEN_CLI_COMPLETE__ARG_IDX="$$comp__arg_idx" \\
       |    OXYGEN_CLI_COMPLETE__ACC_ARGS="$$comp__acc_args" \\
       |    OXYGEN_CLI_COMPLETE__JOIN_STR="$$comp__join_str" \\
       |    ${if isNative then "" else "java -jar "}$targetPath --: complete \\
       |  )
       |  comp__return_code="$$?"
       |
       |  if [[ $$comp__return_code -ne 0 ]]; then
       |    echo "error during command completion (exit $$comp__return_code)" >&2
       |    echo "$$comp__raw_result" >&2
       |    return $$comp__return_code
       |  fi
       |
       |  if [[ -z "$$comp__raw_result" ]]; then
       |    COMPREPLY=()
       |    return 0
       |  fi
       |
       |  # bash 3.2+ / macOS compatible split (no mapfile, no gawk)
       |  COMPREPLY=()
       |  local _rest="$$comp__raw_result"
       |  local _part
       |  while [[ "$$_rest" == *"$$comp__join_str"* ]]; do
       |    _part="$${_rest%%"$$comp__join_str"*}"
       |    COMPREPLY+=("$$_part")
       |    _rest="$${_rest#*"$$comp__join_str"}"
       |  done
       |  [[ -n "$$_rest" ]] && COMPREPLY+=("$$_rest")
       |
       |  # Preserve the program's ordering (positional/commands before flags) instead of bash's
       |  # default alphabetical menu sort. Ignored on bash < 4.4 (e.g. stock macOS bash).
       |  compopt -o nosort 2>/dev/null
       |
       |  local _comp
       |  for _comp in "$${COMPREPLY[@]}"; do
       |    if [[ "$$_comp" == */ ]]; then
       |      compopt -o nospace 2>/dev/null
       |      break
       |    fi
       |  done
       |
       |  return 0
       |}
       |
       |""".stripMargin + end
  }

  private def generateScript(programArgs: List[String]): Task[Unit] =
    for {
      path <- JarUtils.getJarFile
      absoluteSelfPath <- ZIO.attempt(Paths.get(path).toAbsolutePath)
      selfFileName <- ZIO.attempt(absoluteSelfPath.getFileName.toString)
      absolutePathString = absoluteSelfPath.toString
      strippedFileName = selfFileName.stripSuffix(".jar")
      jarSiblingBashPath = absolutePathString.stripSuffix(".jar") + ".sh"
      isNative = !selfFileName.endsWith(".jar")
      scriptText = generateScriptText(absolutePathString, jarSiblingBashPath, isNative, strippedFileName, programArgs)
      _ <-
        if isNative then Console.printLine(scriptText)
        else
          for {
            _ <- ZIO.attempt(Files.write(Paths.get(jarSiblingBashPath), scriptText.getBytes(StandardCharsets.UTF_8))).unit
            _ <- Command("chmod")("+x", jarSiblingBashPath).executeSuccess()
            _ <- Console.printLine(s"\nGenerated script at: $jarSiblingBashPath\nSource with:\n\n. $jarSiblingBashPath --: export\n")
          } yield ()
    } yield ()

  private def getEnvVar[A: StringDecoder as dec](key: String): Task[A] =
    System.env(key).someOrFail(new RuntimeException(s"Missing expected env-var '$key'")).flatMap { valueStr =>
      dec.decodeSimple(valueStr) match
        case Right(value) => ZIO.succeed(value)
        case Left(error)  => ZIO.fail(new RuntimeException(s"Error decoding env-var '$key': $error"))
    }

  private def autoComplete(app: CompiledCliApp[?, ?]): Task[Unit] =
    for {
      n <- getEnvVar[Int](CompletionRequest.numWordsEnv)
      i <- getEnvVar[Int](CompletionRequest.argIdxEnv)
      a <- getEnvVar[String](CompletionRequest.accArgsEnv)
      j <- getEnvVar[String](CompletionRequest.joinStrEnv)
      args = a.detailedSplit(scala.util.matching.Regex.quote(j).r, true, true).toList
      _ <- ZIO.fail(new RuntimeException(s"bad completion args: expected $n words, got ${args.length}")).unless(args.length == n && i < n)
      // Positional suggestions (and sub-command names) first, then named/flag suggestions (`-`-prefixed),
      // each group sorted — rather than one flat alphabetical sort that interleaves them.
      out <- app.complete(CompletionRequest(n, i, args, j)).map { raw =>
        val (named, positional) = raw.distinct.partition(_.startsWith("-"))
        positional.sorted ::: named.sorted
      }
      _ <- Console.printLine(out.mkString(j))
    } yield ()

  def handleArgs(args: List[String], app: CompiledCliApp[?, ?]): IO[AutoCompleteError, Unit] = args match
    case "generate" :: rest =>
      generateScript(rest match
        case "--oxygen-args" :: p => p :+ "--"
        case "--args" :: p        => p
        case Nil                  => Nil
        case _                    => Nil).mapError(AutoCompleteError.ProgramError(_))
    case "complete" :: Nil => autoComplete(app).mapError(AutoCompleteError.ProgramError(_))
    case _                 => ZIO.fail(AutoCompleteError.Help("supported: generate, complete"))

}
