#!/bin/bash

CYAN='\033[0;36m'
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

print_header() {
  local color="$1"
  local msg="$2"

  printf "\n${color}--- $msg ---${NC}\n\n"
}

# assert $1 == '-v'
if [ "$1" != "-v" ]; then
  echo "${RED}Usage: $0 -v <version>${NC}"
  exit 1
fi

if [ -z "$2" ]; then
  echo "${RED}Error: version argument is required${NC}"
  exit 1
fi

tag_version=$2

print_header "$CYAN" "Pulling" && \
git pull origin main && \
print_header "$CYAN" "Tagging" && \
git tag "$tag_version" && \
print_header "$CYAN" "Pushing" && \
git push origin HEAD:main --tags
